name: space_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  intro_screen_onboarding_flutter: ^1.0.0

  # TODO : comments to be added 
  flutter_screenutil: ^5.9.0
  flutter_native_splash: ^2.4.0
  introduction_screen: ^3.1.14
  lottie: ^3.1.0
  persistent_bottom_nav_bar: ^5.0.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/json/

  fonts:
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-Regular.ttf
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
    - family: Orienta
      fonts:
        - asset: assets/fonts/Orienta-Regular.ttf